CREATE TABLE IF NOT EXISTS public."STUDENTS"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    faculty_id integer NOT NULL,
    specialty_id integer NOT NULL,
    course integer NOT NULL,
    gpa integer NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (id)
)
